=pod

=encoding UTF-8

=head2 НАСТРОЙКА

=head3 Установка модулей

apt-get install 
postgresql
redis-server
apache2
apache2-dev
apache2-utils
libapache-dbi-perl
libapache2-mod-perl2
libapache2-mod-perl2-dev
libaprutil1-dbd-pgsql
libdigest-sha-perl
libconfig-tiny-perl
libtemplate-perl
libredis-perl
mcrypt

=head3 Создание БД

CREATE DATABASE apacheauth;

CREATE USER apache WITH password 'ooo';

GRANT ALL privileges ON DATABASE apacheauth TO apache;

=head3 Настройка доступа к БД

host    apacheauth      apache          127.0.0.1/32            trust

=head3 Настройка apache

Добавить в httpd.conf

Include /var/www/my.host.com/etc/apache2/host.conf

=head1 ИСТОРИЯ

Окт 28 14:52:42 EEST 2017

=cut



