=pod

=encoding UTF-8

=head1 НАЗВАНИЕ

Настройка

=head1 ОПИСАНИЕ

=head1 НАСТРОЙКА

 apt-get install libdigest-sha-perl mcrypt libaprutil1-dbd-pgsql postgresql postgresql-contrib apache2 apache2-bin apache2-data apache2-dev apache2-utils

----------------------------------------------------------------------------

## pg
  
  CREATE DATABASE apacheauth;
 
  CREATE USER apache WITH password 'ooo';
  
  GRANT ALL privileges ON DATABASE apacheauth TO apache;

## add to pg_hba.conf
 host    apacheauth      apache          127.0.0.1/32            trust

## pa

## load dump wm/etc/apacheauth.sql
 sudo -u postgres psql -h 127.0.0.1 -d apacheauth -U apache -f wm/etc/apacheauth.sql

----------------------------------------------------------------------------

=head1 ИСТОРИЯ

Окт 28 14:52:42 EEST 2017

=cut



