=pod

=encoding UTF-8

=head1 NAME

TODO

=head1 DESCRIPTION

1. Считать length контанта передаваемого пользователю в Tpl и добавлятьв Headers ответа.
2. Добавить регулирование времени через которое логин будет удалён, если юзер не логинился.
3. Добавить проверку email (Validator)
4. Добавить восстановление пароля / редактирование пароля / подтверждение email.
5. Добавить историю обращений к серверу.
6. is_login true/false.

7. Разграниечение по группам.
8. REST JSON интерфейс + Swagger.
9. Блокировка юзера через is_login true/false.
10. Протестировать вариант удалённого сервера авторизации (PostgreSQL на другом серевер). SSL шифрование уже встроино.

=cut
