=pod

=encoding UTF-8

=head1 NAME

Тестовое задание w-m.ru

=head1 DESCRIPTION

Есть веб-страница, доступ к которой должен быть разрешен только зарегистрированным пользователям. Логины/пароли хранятся в базе данных, доступ организуется с помощью cookies, все страницы отдаются динамически (perl).

=head1 Нужно организовать:

=over 2

=item *

Страницу регистрации нового пользователя.

=item *

Страницу для ввода логина/пароля.

=item *

Страницу с ограниченным доступом.

=item *

Страницу "logout".

=item *

Автоматическое удаление из базы пользователей, которые не логинились в течение последних 3 месяцев.

=item *

При решении задания приветствуется использование технологий работы с шаблонами и стандартными библиотеками, современных веб-фреймворков, AJAX/JSON, БД PostgreSQL.

=item *

Страница регистрации и страница ввода логина/пароля должны содержать клиентсайд-валидацию полей перед отправкой на сервер.
Базовые требования: логин начинается с буквы и состоит не менее чем из трех символов, пароль непустой и состоит не менее чем из трех символов.

=item *

К решению приложить все необходимое для создания БД и развертывания/запуска приложения.

=back

=head1 HISTORY

Окт 28 13:54:42 EEST 2017

=cut
